name: Build CI

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmpv-dev libsqlite3-dev libmecab-dev mecab-ipadic libjson-c-dev libzip-dev mesa-common-dev

    - name: Install Qt 6.9
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.*'
        host: 'linux'
        target: 'desktop'
        install-deps: 'true'

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DMEMENTO_OCR_SUPPORT=OFF -DMEMENTO_MECAB_SUPPORT=ON -DMEMENTO_WERROR=ON -DQT_NO_PRIVATE_MODULE_WARNING=OFF
        cmake --build . -j $(nproc)

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-git
          mingw-w64-ucrt-x86_64-json-c
          mingw-w64-ucrt-x86_64-libzip
          mingw-w64-ucrt-x86_64-mecab
          mingw-w64-ucrt-x86_64-mpv
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-python
          mingw-w64-ucrt-x86_64-qt6
          mingw-w64-ucrt-x86_64-sqlite3

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DMEMENTO_OCR_SUPPORT=OFF -DMEMENTO_MECAB_SUPPORT=ON -DMEMENTO_WERROR=ON
        cmake --build . -j $(nproc)

  macos:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      run: |
        brew update || true
        brew install git cmake sqlite3 qt6 qcoro6 mpv mecab mecab-ipadic json-c libzip || true

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: CMake Build
      run: |
        mkdir build
        cd build
        cmake .. -DMEMENTO_OCR_SUPPORT=OFF -DMEMENTO_MECAB_SUPPORT=ON -DMEMENTO_SYSTEM_QCORO=ON -DMEMENTO_BUNDLE=ON -DMEMENTO_WERROR=ON
        cmake --build . --target memento_bundle -j$(sysctl -n hw.ncpu)
